# Generated by Django 3.1.5 on 2021-01-21 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('show_txt', models.TextField()),
                ('body_txt', models.TextField()),
                ('writer', models.CharField(max_length=30)),
                ('pic', models.ImageField(upload_to='media')),
                ('date', models.DateField(max_length=30)),
            ],
        ),
    ]
