# Generated by Django 3.1.5 on 2021-01-23 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='cat_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='news',
            name='cat_name',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AddField(
            model_name='news',
            name='show',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='news',
            name='body_txt',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='news',
            name='show_txt',
            field=models.TextField(default='-'),
        ),
    ]
