# Generated by Django 3.1.5 on 2021-01-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20210123_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='picname',
            field=models.TextField(default='.'),
        ),
        migrations.AlterField(
            model_name='news',
            name='picurl',
            field=models.TextField(default='.'),
        ),
    ]
