# Generated by Django 3.1.5 on 2021-01-24 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20210123_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='picname',
            new_name='pic',
        ),
        migrations.RemoveField(
            model_name='news',
            name='picurl',
        ),
    ]
