# Generated by Django 3.1.5 on 2021-01-24 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20210124_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='cat_id',
            field=models.IntegerField(default='-'),
        ),
    ]
