# Generated by Django 3.1.5 on 2021-01-24 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20210124_0857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='cat_id',
        ),
    ]
