# Generated by Django 3.1.5 on 2021-01-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_remove_news_cat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='pic',
        ),
        migrations.AddField(
            model_name='news',
            name='picname',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='news',
            name='picurl',
            field=models.TextField(default='-'),
        ),
    ]
