# Generated by Django 3.1.5 on 2021-01-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_news_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='cat_id',
            field=models.IntegerField(default=0),
        ),
    ]
