# Generated by Django 3.1.6 on 2021-02-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
