# Generated by Django 3.1.5 on 2021-01-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='.', max_length=30)),
                ('about', models.TextField(default='.')),
                ('fb', models.CharField(default='.', max_length=30)),
                ('tw', models.CharField(default='.', max_length=30)),
                ('yt', models.CharField(default='.', max_length=30)),
                ('tell', models.BigIntegerField(default=4466456454)),
                ('link', models.CharField(default='.', max_length=30)),
                ('set_name', models.CharField(default='.', max_length=30)),
            ],
        ),
    ]
