# Generated by Django 3.1.6 on 2021-02-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210219_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='picname2',
            field=models.TextField(default='.'),
        ),
    ]
