# Generated by Django 3.1.6 on 2021-02-02 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trending', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trending',
            old_name='name',
            new_name='txt',
        ),
    ]
